version: "3"
services:
  db:
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer:4.6-standalone
    ports:
      - "8080:8080"
